export * from "./interpolate";
export * from "./lifecycle";
export * from "./createAnimationNode";
export * from "./normalize";
export * from "./setAnimationValue";
export * from "./interpolateColor";
export * from "./interpolateValue";
export * from "./getExtrapolationValue";
export * from "./createInterpolationNode";
